In [52]:
## antes de nada cargar los archivos "Reservas_22_23.csv" y "CAT_HABITACIONES.csv" de la documentación inicial

In [53]:
import pandas as pd

In [54]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [55]:
#lectura de datos

#df_reservas=pd.read_csv("/content/Reservas_22_23.csv", sep=";")
df_reservas=pd.read_csv("/content/drive/MyDrive/Reservas_22_23.csv", sep=";")

In [56]:
df_reservas.shape

(1337983, 42)

In [57]:
df_reservas

,ID_RESERVA,ID_HOTEL,LLEGADA,SALIDA,NOCHES,REGIMEN,ID_TIPO,TIPO,USO,PAX,ADULTOS,NENES,BEBES,ID_CLIENTE,TIPO_CLIENTE,CLIENTE,ID_MULTIPLE,ID_MONEDA,MONEDA,STATUS,ID_MOTIVO,ID_CARDEX,SUPLETORIA,CUNAS,FECHA_TOMA,FECHA_MOD,FECHA_CANCELACION,ID_FIDELIDAD,FIDELIDAD,VALHAB,VALPEN,VALSERV,VALFIJOS,COMERCIALIZADORA,CMVALHAB,CMVALPEN,CMCVALSERV,AUTORIZO,GRATIS,PAIS,SEGMENTO,FUENTE_NEGOCIO
0,484750709201,92,2022-07-05 00:00:00.000,2022-07-11 00:00:00.000,6,All Inclusive,37000,JAM Junior Suite OFV,2,4,3,1,0,19686200,1,PALLADIUM TRAVEL CLUB_SOCIOS,0,700,Dólar,9,0,0,0,0,2022-05-22 00:00:00.000,2022-05-30 00:00:00.000,NaN,0,NaN,1460.70,798.00,0.0,0.00,0,1460.70,798.00,0.0,1,0,CANADA,Fixed rates,DIRECT SALES
1,456094009201,92,2022-12-28 00:00:00.000,2023-01-04 00:00:00.000,7,All Inclusive,23300,LH Ambassador Suite BSOV,2,3,2,1,0,19686200,1,PALLADIUM TRAVEL CLUB_SOCIOS,0,700,Dólar,1,0,60444109200,0,0,2022-01-13 00:00:00.000,2022-12-28 00:00:00.000,NaN,0,NaN,1868.00,708.00,0.0,0.00,0,1868.00,708.00,0.0,1,0,ESTADOS UNIDOS,Fixed rates,DIRECT SALES
2,425835909201,92,2022-01-22 00:00:00.000,2022-01-29 00:00:00.000,7,All Inclusive,43800,LH Junior Suite GV,2,3,2,1,0,19686200,1,PALLADIUM TRAVEL CLUB_SOCIOS,0,700,Dólar,3,0,0,0,0,2021-07-13 00:00:00.000,2022-01-20 00:00:00.000,2022-01-20 00:00:00.000,0,NaN,1329.30,665.00,0.0,0.00,0,1329.30,665.00,0.0,1,0,ESTADOS UNIDOS,Fixed rates,DIRECT SALES
3,549929510601,106,2023-11-06 00:00:00.000,2023-11-14 00:00:00.000,8,All Inclusive,42000,TRS Junior Suite PS,2,2,2,0,0,19686200,1,PALLADIUM TRAVEL CLUB_SOCIOS,0,700,Dólar,3,0,0,0,0,2023-04-17 00:00:00.000,2023-11-07 04:27:02.000,2023-10-17 00:00:00.000,0,NaN,1146.56,1146.56,0.0,12.48,0,1146.56,1146.56,0.0,1,0,CANADA,Fixed rates,DIRECT SALES
4,519229110601,106,2023-11-06 00:00:00.000,2023-11-23 00:00:00.000,17,All Inclusive,42000,TRS Junior Suite PS,2,2,2,0,0,19686200,1,PALLADIUM TRAVEL CLUB_SOCIOS,0,700,Dólar,3,0,0,0,0,2023-02-22 12:48:29.000,2023-11-07 04:27:15.000,2023-09-14 00:00:00.000,0,NaN,2436.44,2436.44,0.0,26.52,0,2436.44,2436.44,0.0,1,0,ESTADOS UNIDOS,Fixed rates,DIRECT SALES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1337978,489158800601,6,2022-08-06 00:00:00.000,2022-08-09 00:00:00.000,3,All Inclusive,47400,PVR Junior Suite GV,2,2,2,0,0,19686200,1,PALLADIUM TRAVEL CLUB_SOCIOS,0,700,Dólar,1,0,32684500600,0,0,2022-06-09 00:00:00.000,2022-08-06 00:00:00.000,NaN,0,NaN,595.98,0.00,0.0,0.00,0,595.98,0.00,0.0,1,0,MEXICO,Fixed Rates,DIRECT SALES
1337979,422946710701,107,2022-02-16 00:00:00.000,2022-02-23 00:00:00.000,7,All Inclusive,30800,BAV Ambassador Suite POV,2,2,2,0,0,19700600,1,PALLADIUM TRAVEL CLUB_SEMANA BENEFICIO,0,700,Dólar,1,0,42049410700,0,0,2021-06-27 00:00:00.000,2022-02-16 00:00:00.000,NaN,0,NaN,317.52,448.00,0.0,0.00,1,1869.70,448.00,0.0,1,0,FRANCIA,Fixed Rates,DIRECT SALES
1337980,531037108301,83,2023-02-09 00:00:00.000,2023-02-16 00:00:00.000,7,All Inclusive,47600,SSA Junior Suite GV,2,3,3,0,0,19686200,1,PALLADIUM TRAVEL CLUB_SOCIOS,0,700,Dólar,3,0,0,0,0,2023-01-23 00:00:00.000,2023-02-05 00:00:00.000,2023-02-05 00:00:00.000,0,NaN,3255.84,630.00,0.0,0.00,0,3255.84,630.00,0.0,1,0,ARGENTINA,Fixed rates,DIRECT SALES
1337981,482275810601,106,2023-02-09 00:00:00.000,2023-02-16 00:00:00.000,7,All Inclusive,13000,COL Junior Suite GV,2,2,2,0,0,19686200,1,PALLADIUM TRAVEL CLUB_SOCIOS,0,700,Dólar,3,0,0,0,0,2022-05-12 00:00:00.000,2022-11-11 00:00:00.000,2022-11-11 00:00:00.000,0,NaN,1854.16,0.00,0.0,9.80,0,1854.16,0.00,0.0,1,0,CANADA,Fixed rates,DIRECT SALES
1337982,475726909901,99,2022-12-13 00:00:00.000,2022-12-21 00:00:00.000,8,All Inclusive,32700,CAP Ambassador ST PS OV,2,2,2,0,0,19686200,1,PALLADIUM TRAVEL CLUB_SOCIOS,0,700,Dólar,3,0,0,0,0,2022-04-08 00:00:00.000,2022-04-21 00:00:00.000,2022-04-21 00:00:00.000,0,NaN,3236.80,688.00,0.0,0.00,0,3236.80,688.00,0.0,1,0,ESTADOS UNIDOS,Fixed rates,DIRECT SALES

In [58]:
#comprobamos valores nulos
df_reservas.isnull().sum()

ID_RESERVA                 0
ID_HOTEL                   0
LLEGADA                    0
SALIDA                     0
NOCHES                     0
REGIMEN                   17
ID_TIPO                    0
TIPO                       0
USO                        0
PAX                        0
ADULTOS                    0
NENES                      0
BEBES                      0
ID_CLIENTE                 0
TIPO_CLIENTE               0
CLIENTE                    8
ID_MULTIPLE                0
ID_MONEDA                  0
MONEDA                     0
STATUS                     0
ID_MOTIVO                  0
ID_CARDEX                  0
SUPLETORIA                 0
CUNAS                      0
FECHA_TOMA                 0
FECHA_MOD                280
FECHA_CANCELACION     899395
ID_FIDELIDAD               0
FIDELIDAD            1126954
VALHAB                     0
VALPEN                     0
VALSERV                    0
VALFIJOS                   0
COMERCIALIZADORA           0
CMVALHAB                   0
CMVALPEN                   0
CMCVALSERV                 0
AUTORIZO                   0
GRATIS                     0
PAIS                       0
SEGMENTO                   0
FUENTE_NEGOCIO             0
dtype: int64

In [59]:
#decidimos eliminar las filas con valores nulos de las variables REGIMEN y CLIENTE
df_reservas_0 = df_reservas.dropna(subset=['REGIMEN', 'CLIENTE'])

In [60]:
df_reservas_0.isnull().sum()

ID_RESERVA                 0
ID_HOTEL                   0
LLEGADA                    0
SALIDA                     0
NOCHES                     0
REGIMEN                    0
ID_TIPO                    0
TIPO                       0
USO                        0
PAX                        0
ADULTOS                    0
NENES                      0
BEBES                      0
ID_CLIENTE                 0
TIPO_CLIENTE               0
CLIENTE                    0
ID_MULTIPLE                0
ID_MONEDA                  0
MONEDA                     0
STATUS                     0
ID_MOTIVO                  0
ID_CARDEX                  0
SUPLETORIA                 0
CUNAS                      0
FECHA_TOMA                 0
FECHA_MOD                280
FECHA_CANCELACION     899380
ID_FIDELIDAD               0
FIDELIDAD            1126941
VALHAB                     0
VALPEN                     0
VALSERV                    0
VALFIJOS                   0
COMERCIALIZADORA           0
CMVALHAB                   0
CMVALPEN                   0
CMCVALSERV                 0
AUTORIZO                   0
GRATIS                     0
PAIS                       0
SEGMENTO                   0
FUENTE_NEGOCIO             0
dtype: int64

In [61]:
#comprobamos el tipo de dato de cada columna
df_reservas_0.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1337958 entries, 0 to 1337982
Data columns (total 42 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   ID_RESERVA         1337958 non-null  int64
 1   ID_HOTEL           1337958 non-null  int64
 2   LLEGADA            1337958 non-null  object
 3   SALIDA             1337958 non-null  object
 4   NOCHES             1337958 non-null  int64
 5   REGIMEN            1337958 non-null  object
 6   ID_TIPO            1337958 non-null  int64
 7   TIPO               1337958 non-null  object
 8   USO                1337958 non-null  int64
 9   PAX                1337958 non-null  int64
 10  ADULTOS            1337958 non-null  int64
 11  NENES              1337958 non-null  int64
 12  BEBES              1337958 non-null  int64
 13  ID_CLIENTE         1337958 non-null  int64
 14  TIPO_CLIENTE       1337958 non-null  int64
 15  CLIENTE            1337958 non-null  object
 16  ID_MULTIPLE        1337958 non-null  int64
 17  ID_MONEDA          1337958 non-null  int64
 18  MONEDA             1337958 non-null  object
 19  STATUS             1337958 non-null  int64
 20  ID_MOTIVO          1337958 non-null  int64
 21  ID_CARDEX          1337958 non-null  int64
 22  SUPLETORIA         1337958 non-null  int64
 23  CUNAS              1337958 non-null  int64
 24  FECHA_TOMA         1337958 non-null  object
 25  FECHA_MOD          1337678 non-null  object
 26  FECHA_CANCELACION  438578 non-null   object
 27  ID_FIDELIDAD       1337958 non-null  int64
 28  FIDELIDAD          211017 non-null   object
 29  VALHAB             1337958 non-null  float64
 30  VALPEN             1337958 non-null  float64
 31  VALSERV            1337958 non-null  float64
 32  VALFIJOS           1337958 non-null  float64
 33  COMERCIALIZADORA   1337958 non-null  int64
 34  CMVALHAB           1337958 non-null  float64
 35  CMVALPEN           1337958 non-null  float64
 36  CMCVALSERV         1337958 non-null  float64
 37  AUTORIZO           1337958 non-null  int64
 38  GRATIS             1337958 non-null  int64
 39  PAIS               1337958 non-null  object
 40  SEGMENTO           1337958 non-null  object
 41  FUENTE_NEGOCIO     1337958 non-null  object
dtypes: float64(7), int64(22), object(13)
memory usage: 438.9+ MB

In [62]:
df_reservas_0.head(3)

,ID_RESERVA,ID_HOTEL,LLEGADA,SALIDA,NOCHES,REGIMEN,ID_TIPO,TIPO,USO,PAX,ADULTOS,NENES,BEBES,ID_CLIENTE,TIPO_CLIENTE,CLIENTE,ID_MULTIPLE,ID_MONEDA,MONEDA,STATUS,ID_MOTIVO,ID_CARDEX,SUPLETORIA,CUNAS,FECHA_TOMA,FECHA_MOD,FECHA_CANCELACION,ID_FIDELIDAD,FIDELIDAD,VALHAB,VALPEN,VALSERV,VALFIJOS,COMERCIALIZADORA,CMVALHAB,CMVALPEN,CMCVALSERV,AUTORIZO,GRATIS,PAIS,SEGMENTO,FUENTE_NEGOCIO
0,484750709201,92,2022-07-05 00:00:00.000,2022-07-11 00:00:00.000,6,All Inclusive,37000,JAM Junior Suite OFV,2,4,3,1,0,19686200,1,PALLADIUM TRAVEL CLUB_SOCIOS,0,700,Dólar,9,0,0,0,0,2022-05-22 00:00:00.000,2022-05-30 00:00:00.000,NaN,0,NaN,1460.7,798.0,0.0,0.0,0,1460.7,798.0,0.0,1,0,CANADA,Fixed rates,DIRECT SALES
1,456094009201,92,2022-12-28 00:00:00.000,2023-01-04 00:00:00.000,7,All Inclusive,23300,LH Ambassador Suite BSOV,2,3,2,1,0,19686200,1,PALLADIUM TRAVEL CLUB_SOCIOS,0,700,Dólar,1,0,60444109200,0,0,2022-01-13 00:00:00.000,2022-12-28 00:00:00.000,NaN,0,NaN,1868.0,708.0,0.0,0.0,0,1868.0,708.0,0.0,1,0,ESTADOS UNIDOS,Fixed rates,DIRECT SALES
2,425835909201,92,2022-01-22 00:00:00.000,2022-01-29 00:00:00.000,7,All Inclusive,43800,LH Junior Suite GV,2,3,2,1,0,19686200,1,PALLADIUM TRAVEL CLUB_SOCIOS,0,700,Dólar,3,0,0,0,0,2021-07-13 00:00:00.000,2022-01-20 00:00:00.000,2022-01-20 00:00:00.000,0,NaN,1329.3,665.0,0.0,0.0,0,1329.3,665.0,0.0,1,0,ESTADOS UNIDOS,Fixed rates,DIRECT SALES

In [63]:
# 1. Convertir la columna "LLEGADA" a formato fecha
df_reservas_0['LLEGADA'] = pd.to_datetime(df_reservas_0['LLEGADA'])

# 2. Extraer únicamente la fecha descartando la hora
df_reservas_0['LLEGADA'] = df_reservas_0['LLEGADA'].dt.date

/tmp/ipykernel_2762/782344380.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_reservas_0['LLEGADA'] = pd.to_datetime(df_reservas_0['LLEGADA'])
/tmp/ipykernel_2762/782344380.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_reservas_0['LLEGADA'] = df_reservas_0['LLEGADA'].dt.date

In [64]:
# 1. Convertir la columna "SALIDA" a formato fecha
df_reservas_0['SALIDA'] = pd.to_datetime(df_reservas_0['SALIDA'])

# 2. Extraer únicamente la fecha descartando la hora
df_reservas_0['SALIDA'] = df_reservas_0['SALIDA'].dt.date

/tmp/ipykernel_2762/1777435722.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_reservas_0['SALIDA'] = pd.to_datetime(df_reservas_0['SALIDA'])
/tmp/ipykernel_2762/1777435722.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_reservas_0['SALIDA'] = df_reservas_0['SALIDA'].dt.date

In [65]:
df_reservas_0

,ID_RESERVA,ID_HOTEL,LLEGADA,SALIDA,NOCHES,REGIMEN,ID_TIPO,TIPO,USO,PAX,ADULTOS,NENES,BEBES,ID_CLIENTE,TIPO_CLIENTE,CLIENTE,ID_MULTIPLE,ID_MONEDA,MONEDA,STATUS,ID_MOTIVO,ID_CARDEX,SUPLETORIA,CUNAS,FECHA_TOMA,FECHA_MOD,FECHA_CANCELACION,ID_FIDELIDAD,FIDELIDAD,VALHAB,VALPEN,VALSERV,VALFIJOS,COMERCIALIZADORA,CMVALHAB,CMVALPEN,CMCVALSERV,AUTORIZO,GRATIS,PAIS,SEGMENTO,FUENTE_NEGOCIO
0,484750709201,92,2022-07-05,2022-07-11,6,All Inclusive,37000,JAM Junior Suite OFV,2,4,3,1,0,19686200,1,PALLADIUM TRAVEL CLUB_SOCIOS,0,700,Dólar,9,0,0,0,0,2022-05-22 00:00:00.000,2022-05-30 00:00:00.000,NaN,0,NaN,1460.70,798.00,0.0,0.00,0,1460.70,798.00,0.0,1,0,CANADA,Fixed rates,DIRECT SALES
1,456094009201,92,2022-12-28,2023-01-04,7,All Inclusive,23300,LH Ambassador Suite BSOV,2,3,2,1,0,19686200,1,PALLADIUM TRAVEL CLUB_SOCIOS,0,700,Dólar,1,0,60444109200,0,0,2022-01-13 00:00:00.000,2022-12-28 00:00:00.000,NaN,0,NaN,1868.00,708.00,0.0,0.00,0,1868.00,708.00,0.0,1,0,ESTADOS UNIDOS,Fixed rates,DIRECT SALES
2,425835909201,92,2022-01-22,2022-01-29,7,All Inclusive,43800,LH Junior Suite GV,2,3,2,1,0,19686200,1,PALLADIUM TRAVEL CLUB_SOCIOS,0,700,Dólar,3,0,0,0,0,2021-07-13 00:00:00.000,2022-01-20 00:00:00.000,2022-01-20 00:00:00.000,0,NaN,1329.30,665.00,0.0,0.00,0,1329.30,665.00,0.0,1,0,ESTADOS UNIDOS,Fixed rates,DIRECT SALES
3,549929510601,106,2023-11-06,2023-11-14,8,All Inclusive,42000,TRS Junior Suite PS,2,2,2,0,0,19686200,1,PALLADIUM TRAVEL CLUB_SOCIOS,0,700,Dólar,3,0,0,0,0,2023-04-17 00:00:00.000,2023-11-07 04:27:02.000,2023-10-17 00:00:00.000,0,NaN,1146.56,1146.56,0.0,12.48,0,1146.56,1146.56,0.0,1,0,CANADA,Fixed rates,DIRECT SALES
4,519229110601,106,2023-11-06,2023-11-23,17,All Inclusive,42000,TRS Junior Suite PS,2,2,2,0,0,19686200,1,PALLADIUM TRAVEL CLUB_SOCIOS,0,700,Dólar,3,0,0,0,0,2023-02-22 12:48:29.000,2023-11-07 04:27:15.000,2023-09-14 00:00:00.000,0,NaN,2436.44,2436.44,0.0,26.52,0,2436.44,2436.44,0.0,1,0,ESTADOS UNIDOS,Fixed rates,DIRECT SALES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1337978,489158800601,6,2022-08-06,2022-08-09,3,All Inclusive,47400,PVR Junior Suite GV,2,2,2,0,0,19686200,1,PALLADIUM TRAVEL CLUB_SOCIOS,0,700,Dólar,1,0,32684500600,0,0,2022-06-09 00:00:00.000,2022-08-06 00:00:00.000,NaN,0,NaN,595.98,0.00,0.0,0.00,0,595.98,0.00,0.0,1,0,MEXICO,Fixed Rates,DIRECT SALES
1337979,422946710701,107,2022-02-16,2022-02-23,7,All Inclusive,30800,BAV Ambassador Suite POV,2,2,2,0,0,19700600,1,PALLADIUM TRAVEL CLUB_SEMANA BENEFICIO,0,700,Dólar,1,0,42049410700,0,0,2021-06-27 00:00:00.000,2022-02-16 00:00:00.000,NaN,0,NaN,317.52,448.00,0.0,0.00,1,1869.70,448.00,0.0,1,0,FRANCIA,Fixed Rates,DIRECT SALES
1337980,531037108301,83,2023-02-09,2023-02-16,7,All Inclusive,47600,SSA Junior Suite GV,2,3,3,0,0,19686200,1,PALLADIUM TRAVEL CLUB_SOCIOS,0,700,Dólar,3,0,0,0,0,2023-01-23 00:00:00.000,2023-02-05 00:00:00.000,2023-02-05 00:00:00.000,0,NaN,3255.84,630.00,0.0,0.00,0,3255.84,630.00,0.0,1,0,ARGENTINA,Fixed rates,DIRECT SALES
1337981,482275810601,106,2023-02-09,2023-02-16,7,All Inclusive,13000,COL Junior Suite GV,2,2,2,0,0,19686200,1,PALLADIUM TRAVEL CLUB_SOCIOS,0,700,Dólar,3,0,0,0,0,2022-05-12 00:00:00.000,2022-11-11 00:00:00.000,2022-11-11 00:00:00.000,0,NaN,1854.16,0.00,0.0,9.80,0,1854.16,0.00,0.0,1,0,CANADA,Fixed rates,DIRECT SALES
1337982,475726909901,99,2022-12-13,2022-12-21,8,All Inclusive,32700,CAP Ambassador ST PS OV,2,2,2,0,0,19686200,1,PALLADIUM TRAVEL CLUB_SOCIOS,0,700,Dólar,3,0,0,0,0,2022-04-08 00:00:00.000,2022-04-21 00:00:00.000,2022-04-21 00:00:00.000,0,NaN,3236.80,688.00,0.0,0.00,0,3236.80,688.00,0.0,1,0,ESTADOS UNIDOS,Fixed rates,DIRECT SALES

In [66]:
df_reservas_0["REGIMEN"].value_counts(normalize=True) #OJO variable super desbalanceada, valorar eliminar para el modelo

REGIMEN
All Inclusive             0.960973
Alojamiento y Desayuno    0.026686
Sólo Alojamiento          0.010393
Pensión Completa          0.001237
Media Pensión             0.000712
Name: proportion, dtype: float64

In [67]:
#Se aconseja realizar un modelo con los hoteles más grandes en numero de habitaciones y con más facturación.
#los que tienen ID 107 (PUNTA CANA), 96 COSTA MUJERES, 106 RIVIERA MAYA y 92 JAMAICA.
df_reservas_0["ID_HOTEL"].value_counts(normalize=True)

ID_HOTEL
107    2.290827e-01
96     1.959770e-01
106    1.736205e-01
92     1.540728e-01
6      9.530045e-02
83     9.197822e-02
9      3.689802e-02
99     2.305902e-02
3      9.716299e-06
91     7.474076e-07
85     7.474076e-07
Name: proportion, dtype: float64

In [68]:
#Esta variable es interesante agruparla para reducir opciones, los 3 primeros digitos se refieren al hotel.
df_reservas_0["ID_TIPO"].value_counts(normalize=True)

ID_TIPO
47600    6.966736e-02
47100    4.610907e-02
11200    4.245574e-02
26500    4.011561e-02
45600    3.973742e-02
             ...
44500    5.231853e-06
7700     4.484446e-06
7200     1.494815e-06
5100     7.474076e-07
3500     7.474076e-07
Name: proportion, Length: 173, dtype: float64

In [69]:
#es interesante crear variables que indiquen si la reserva da a la piscina (PS) o al Jardin (GV), si es suite... de tipo boolean
df_reservas_0["TIPO"].value_counts(normalize=True)

TIPO
SSA Junior Suite GV        6.966736e-02
PVR Deluxe Garden View     4.610907e-02
JAM Junior Suite GV        4.245574e-02
CMU Junior Suite GV        4.011561e-02
CMU Junior Suite PS        3.973742e-02
                               ...
Suite Executive            1.494815e-06
COL Romance Villa Suite    7.474076e-07
Suite                      7.474076e-07
Presidencial               7.474076e-07
z. Premium Junior Suite    7.474076e-07
Name: proportion, Length: 196, dtype: float64

In [70]:
# 1. Cargar el CSV
# df_cat = pd.read_csv('/content/CAT_HABITACIONES.csv', sep=';', encoding='utf-8-sig')
df_cat = pd.read_csv('/content/drive/MyDrive/CAT_HABITACIONES.csv', sep=';', encoding='utf-8-sig')

# 2. Seleccionar columnas y eliminar nulos
df_cat = df_cat[['NOMBRE_HABITACION', 'CATEGORIA']]
df_cat = df_cat.dropna(subset=['NOMBRE_HABITACION'])

# --- PASO DE LIMPIEZA CLAVE ---
# Eliminamos espacios al inicio/final y convertimos a mayúsculas en ambos datasets
df_reservas_0['TIPO'] = df_reservas_0['TIPO'].astype(str).str.strip().str.upper()
df_cat['NOMBRE_HABITACION'] = df_cat['NOMBRE_HABITACION'].astype(str).str.strip().str.upper()

# 3. Eliminar duplicados en el catálogo limpio
df_cat = df_cat.drop_duplicates(subset=['NOMBRE_HABITACION'])

# 4. Realizar el cruce (merge)
df_reservas_0 = df_reservas_0.merge(
    df_cat,
    left_on='TIPO',
    right_on='NOMBRE_HABITACION',
    how='left'
)

# 5. Eliminar la columna auxiliar
df_reservas_1 = df_reservas_0.drop(columns=['NOMBRE_HABITACION'])

/tmp/ipykernel_2762/1692564237.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_reservas_0['TIPO'] = df_reservas_0['TIPO'].astype(str).str.strip().str.upper()

In [71]:
#se normaliza la columna "TIPO" con el archivo "CAT_HABITACIONES"
pd.set_option("display.max_columns",None)
df_reservas_1.head(2)

,ID_RESERVA,ID_HOTEL,LLEGADA,SALIDA,NOCHES,REGIMEN,ID_TIPO,TIPO,USO,PAX,ADULTOS,NENES,BEBES,ID_CLIENTE,TIPO_CLIENTE,CLIENTE,ID_MULTIPLE,ID_MONEDA,MONEDA,STATUS,ID_MOTIVO,ID_CARDEX,SUPLETORIA,CUNAS,FECHA_TOMA,FECHA_MOD,FECHA_CANCELACION,ID_FIDELIDAD,FIDELIDAD,VALHAB,VALPEN,VALSERV,VALFIJOS,COMERCIALIZADORA,CMVALHAB,CMVALPEN,CMCVALSERV,AUTORIZO,GRATIS,PAIS,SEGMENTO,FUENTE_NEGOCIO,Categoria
0,484750709201,92,2022-07-05,2022-07-11,6,All Inclusive,37000,JAM JUNIOR SUITE OFV,2,4,3,1,0,19686200,1,PALLADIUM TRAVEL CLUB_SOCIOS,0,700,Dólar,9,0,0,0,0,2022-05-22 00:00:00.000,2022-05-30 00:00:00.000,NaN,0,NaN,1460.7,798.0,0.0,0.0,0,1460.7,798.0,0.0,1,0,CANADA,Fixed rates,DIRECT SALES,Default Category
1,456094009201,92,2022-12-28,2023-01-04,7,All Inclusive,23300,LH AMBASSADOR SUITE BSOV,2,3,2,1,0,19686200,1,PALLADIUM TRAVEL CLUB_SOCIOS,0,700,Dólar,1,0,60444109200,0,0,2022-01-13 00:00:00.000,2022-12-28 00:00:00.000,NaN,0,NaN,1868.0,708.0,0.0,0.0,0,1868.0,708.0,0.0,1,0,ESTADOS UNIDOS,Fixed rates,DIRECT SALES,Default Category

In [72]:
#variable desbalanceada, eliminar para ML
df_reservas_1["CATEGORIA"].value_counts(normalize=True)

df_reservas_1 = df_reservas_1.drop(columns=['CATEGORIA'])

KeyError: 'CATEGORIA'

In [ ]:
df_reservas_1.info()

In [ ]:
#variable no relevante para el modelo, está muy desbalanceada
df_reservas_1["USO"].value_counts(normalize=True)

In [ ]:
df_reservas_1["PAX"].value_counts(normalize=True)

In [ ]:
import numpy as np
# Definir las condiciones
condiciones = [
    df_reservas_1['PAX'] == 1,
    df_reservas_1['PAX'] == 2,
    df_reservas_1['PAX'] > 2
]

# Definir los resultados correspondientes a cada condición
opciones = ['SINGLE', 'PAREJAS', 'FAMILIAS']

# Crear la nueva columna aplicando la lógica
df_reservas_1['PAX_TIPO'] = np.select(condiciones, opciones, default='OTRO')

In [ ]:
df_reservas_1.head(2)

In [ ]:
df_reservas_1["PAX_TIPO"].value_counts(normalize=True)

In [ ]:
#variable no relevante, con la variable creada PAX_TIPO se agrupan los adultos
df_reservas_1["ADULTOS"].value_counts(normalize=False)

In [ ]:
# Conservar solo las filas donde ADULTOS sea diferente de 0
df_reservas_1 = df_reservas_1[df_reservas_1['ADULTOS'] != 0]

In [ ]:
df_reservas_1["ADULTOS"].value_counts(normalize=False)

In [ ]:
df_reservas_1.info()

In [ ]:
#ojo! variable super desbalanceada, valorar eliminar del modelo ML
df_reservas_1["TIPO_CLIENTE"].value_counts(normalize=True)

In [ ]:
pd.set_option("display.max_columns",None)

In [ ]:
df_reservas_1

In [ ]:
#######################################
#NOS HEMOS QUEDADO EN ID_MULTIPLE#
#######################################

In [ ]:
df_reservas_1.info()

In [ ]:
#16-22 DIEGO (done)
#23-30 GUILLERMO
#31-38 ERIK
#39-45 RAUL

In [ ]:
df_reservas_2=df_reservas_1.copy()

In [ ]:
#16-22 DIEGO

In [ ]:
df_reservas_2

In [ ]:
#16. "ID_MULTIPLE"
#de acuerdo al diccionario de datos "ID_MULTIPLE" indica si una reserva es de grupo o no
#ID_MULTIPLE > 0 --> grupo else no grupo
#vamos a crear una variable nueva (columna) que indique de acuerdo a esta logica si es GRUPO / NO GRUPO

In [ ]:
df_reservas_2["ID_MULTIPLE"].value_counts(normalize=True)

In [ ]:
# Creamos la columna 'GRUPO_TIPO' aplicando la condición
df_reservas_2['GRUPO_TIPO'] = np.where(df_reservas_2['ID_MULTIPLE'] > 0, 'GRUPO', 'NO GRUPO')

In [ ]:
df_reservas_2

In [ ]:
df_reservas_2["GRUPO_TIPO"].value_counts(normalize=True)

In [ ]:
#17. "ID_MONEDA"
#Se trata de un identificador del tipo de moneda, variable correlacionada con la columna siguiente "MONEDA"
#Es un float, pero en realidad es una variable categórica, no tiene pinta que la vayamos a usar en el modelo, la dejamos asi.

In [ ]:
df_reservas_2["ID_MONEDA"].value_counts(normalize=True)

In [ ]:
#18. "MONEDA"
#Tipo string (object) que indica la moneda en la que se realiza la reserva.
#La dejamos tal que así, puede ser una variable predictora.
#OJO! Todas las variables de dinero 29,30,31, 34,35 y 36 se deben pasar a Dolares.

In [ ]:
df_reservas_2["MONEDA"].value_counts(normalize=True)

In [ ]:
#19. "STATUS"
#MUY IMPORTANTE!! Esta variable va a ser nuestro TARGET, lo que vamos a intentar predecir.
#De acuerdo al diccionario de datos:
#STATUS =1 Y 2 --> CONFIRMADO
#STATUS =3,4,5 --> CANCELADO

#Siguiendo esta lógica, vamos a crear una variable "STATUS_BOOL" donde:
# 0 --> RESERVA NO CANCELADA
# 1 --> RESERVA CANCELADA

In [ ]:
#vamos a ver la distribucion antes de crear la nueva columna
df_reservas_2["STATUS"].value_counts(normalize=True)

In [ ]:
#eliminamos el valor status=9 porque son reservas que se han modificado
df_reservas_2 = df_reservas_2[df_reservas_2['STATUS'] !=9]

In [ ]:
#Hay un valor "9" que no se recoge en el diccionario de datos, y representa un 14% de nuestra muestra, no podemos eliminarlo
#vamos a tratarlo como RESERVA CANCELADA pero debemos consultar a GUSTAVO.

In [ ]:
# Mapeo actualizado incluyendo el valor 9 como cancelado
mapa_status = {
    1: 0,  # Confirmado
    2: 0,  # Confirmado
    3: 1,  # Cancelado
    4: 1,  # Cancelado
    5: 1,  # Cancelado
    9: 1   # No documentado -> Tratado como Cancelado
}

df_reservas_2['STATUS_BOOL'] = df_reservas_2['STATUS'].map(mapa_status)

In [ ]:
df_reservas_2.head(5)

In [ ]:
df_reservas_2["STATUS_BOOL"].value_counts(normalize=True)

In [ ]:
#20. "ID_MOTIVO"
#De acuerdo al diccionario de datos, se trata de un codigo que identifica el motivo de la cancelacion
#ademas se sugiere que se "traduzca" a una descripcion, siguiendo la siguiente correlacion:

#119300	CANCELACION CLIENTE
#561300	CANCELACION CON CARGO
#678800	CANCELACION POR OBRAS
#119000	CANCELACION TTOO
#119100	DUPLICIDAD RESERVA
#53500	OVERBOOKING

#creamos una nueva columna "MOTIVO_DESCRIPCION" siguiendo esta logica
#No tiene pinta de que la vayamos a usar para predecir la cancelación, en un ejercicio a mayores se puede usar esta variable como TARGET para predecir el motivo de la cancelacion, pero no es el caso.

In [ ]:
#comprobamos la distribucion y que tengamos todos los codigos con su descripcion
df_reservas_2["ID_MOTIVO"].value_counts(normalize=True)

In [ ]:
#Efectivamente no tenemos todos los codigos, por lo que aquellos que no tenemos los definiremos como "OTRO"
# 1. Definimos el diccionario con la relación código-descripción
motivos_dict = {
    119300: 'CANCELACION CLIENTE',
    561300: 'CANCELACION CON CARGO',
    678800: 'CANCELACION POR OBRAS',
    119000: 'CANCELACION TTOO',
    119100: 'DUPLICIDAD RESERVA',
    53500:  'OVERBOOKING'
}

# 2. Aplicamos el mapeo y rellenamos los valores no encontrados con 'OTRO'
df_reservas_2['MOTIVO_DESCRIPCION'] = df_reservas_2['ID_MOTIVO'].map(motivos_dict).fillna('OTRO')

In [ ]:
df_reservas_2["MOTIVO_DESCRIPCION"].value_counts(normalize=True)

In [ ]:
#CON ESTE CODIGO VEMOS LA RELACION ENTRE LA VARIABLE ID_MOTIVO Y "STATUS_BOOL", no termino de entender la relacion
# Opción 1: Tabla cruzada con totales (la forma más visual)
#print(pd.crosstab(
#    index=df_reservas_2['ID_MOTIVO'],
#    columns=df_reservas_2['STATUS_BOOL'],
#    margins=True,          # Añade la fila/columna de "Total"
#    dropna=False           # Muestra también si hay valores nulos (NaN)
#))

In [ ]:
#21. ID_CARDEX
#variable que indica si el usuario que tiene una reserva aceptada ha realizado el check in, no es relevante para el modelo
#no es una variable predictora, no la vamos a usar, la dejamos asi.

In [ ]:
#22. "SUPLETORIA"
#Esta variable indica si la reserva necesita cama supletoria, es de tipo int64, la pasamos a boolean

In [ ]:
#vemos antes la distribucion por si hubiera algo raro
df_reservas_2["SUPLETORIA"].value_counts(normalize=True)

In [ ]:
#Parece que todo OK, aunque es una variable super desbalanceada, no podriamos utilizarla en el modelo, no obstante, la transformamos a boolean.
df_reservas_2['SUPLETORIA'] = df_reservas_2['SUPLETORIA'].astype(bool)

In [ ]:
df_reservas_2.dtypes

In [ ]:
#23-30 GUILLERMO
#CUNAS	FECHA_TOMA	FECHA_MOD	FECHA_CANCELACION	ID_FIDELIDAD	FIDELIDAD	VALHAB
#24	    25	        26	      27	              28	          29	      30
df_reservas_3=df_reservas_2.copy()

In [ ]:
# CUNAS
# Variable binaria que indica si la reserva requiere cuna.
# Tras su transformación a booleano, observamos una distribución muy desbalanceada:
# False = 96,59%
# True = 3,41%
#
# Aunque representa un evento poco frecuente, puede contener información relevante
# sobre reservas familiares y presencia de bebés. No se recomienda eliminarla
# únicamente por su desbalanceo; se evaluará posteriormente su capacidad predictiva

In [ ]:
#elimino los casos de mas de una cuna que son pequeños y la transformo a boolean.
df_reservas_3 = df_reservas_3[df_reservas_3['CUNAS'] <=1]
#convierto a booleano si tienes cunas o no la reserva
df_reservas_3["CUNAS"] = df_reservas_3["CUNAS"].astype(bool)

df_reservas_3["CUNAS"].value_counts(normalize=True)

In [ ]:
# FECHA_TOMA
# Se elimina la componente horaria por no aportar valor al análisis.
#
# ANTELACION_DIAS
# Nueva variable que mide el número de días transcurridos entre la fecha
# de realización de la reserva y la fecha de llegada al hotel.
# Se espera que sea una de las variables con mayor capacidad predictiva
# sobre la cancelación de reservas.
#
# TEMPORADA
# Variable categórica derivada de la fecha de llegada que clasifica
# las reservas según la temporada hotelera (ALTA, MEDIA o BAJA),
# permitiendo capturar efectos de estacionalidad.

In [ ]:
df_reservas_3.info()

In [ ]:
#elimnamos registro con fecha en formato raro 0023-12-25 a 23-12-2025
df_reservas_3 = df_reservas_3[df_reservas_3['FECHA_TOMA'] !='23-12-2025 04:35:26.000']

#Elimino la hora de la fecha, no es relevante
df_reservas_3['FECHA_TOMA'] = pd.to_datetime(df_reservas_3['FECHA_TOMA']).dt.date

df_reservas_3["FECHA_TOMA"].value_counts(normalize=True)

df_reservas_3['ANTELACION_DIAS'] = (
    pd.to_datetime(df_reservas_3['LLEGADA']) -
    pd.to_datetime(df_reservas_3['FECHA_TOMA'])
).dt.days

#
#bins = [-1, 7, 30, 90, 180, 365, 9999]
#labels = [
#    'ULTIMA_SEMANA',
#    '1_MES',
#    '3_MESES',
#    '6_MESES',
#    '1_ANO',
#    'MAS_1_ANO'
#]
#df_reservas_3['ANTELACION_TRAMO'] = pd.cut(
#    df_reservas_3['ANTELACION_DIAS'],
#    bins=bins,
#    labels=labels
#)

In [ ]:
#creo funcion para agrupar en temporadas las fechas de llegada (revisar que es temporada alta/baja en sudamerica)
def temporada_hotel(fecha):

    mes = fecha.month

    if mes in [12,1,2,3,4,5]:
        return 'ALTA'

    elif mes in [6, 10,11]:
        return 'MEDIA'

    else:
        return 'BAJA'

df_reservas_3['TEMPORADA'] = (pd.to_datetime(df_reservas_3['LLEGADA']).apply(temporada_hotel))

In [ ]:
df_reservas_3.head()

In [ ]:
#Elimino la hora de la fecha, no es relevante para el modelo
df_reservas_3['FECHA_MOD'] = pd.to_datetime(df_reservas_3['FECHA_MOD']).dt.date

num_modificadas = df_reservas_3['FECHA_MOD'].notnull().sum()

pct_modificadas = (
    num_modificadas / len(df_reservas_3)
) * 100

print(f"Reservas modificadas: {num_modificadas:,}")
print(f"Porcentaje: {pct_modificadas:.2f}%")

In [ ]:
# FECHA_CANCELACION
# Variable de tipo fecha que indica cuándo una reserva fue cancelada.
# Se observa que 437.932 reservas (32,80%) disponen de fecha de cancelación,
# mientras que el 67,20% restante presenta valores nulos, interpretados como
# reservas no canceladas.
#
# Esta variable se utilizará para construir la variable objetivo (IS_CANCELLED),
# pero no como variable predictora, ya que contiene información posterior al
# momento de la reserva y podría generar data leakage.
#
# El porcentaje de cancelación observado refleja un desbalance moderado,
# adecuado para el entrenamiento de modelos de clasificación.

In [ ]:
#Elimino la hora de la fecha, no es relevante
df_reservas_3['FECHA_CANCELACION'] = pd.to_datetime(df_reservas_3['FECHA_CANCELACION']).dt.date

#creo variable para indicar si está cancelada la habitacion o no
df_reservas_3['IS_CANCELLED'] = df_reservas_3['FECHA_CANCELACION'].notna().astype(int)

num_canceladas = df_reservas_3['FECHA_CANCELACION'].notnull().sum()

pct_cancelado = (
    num_canceladas / len(df_reservas_3)
) * 100

print(f"Reservas canceladas: {num_canceladas:,}")
print(f"Porcentaje: {pct_cancelado:.2f}%")

df_reservas_3["FECHA_CANCELACION"].value_counts(normalize=True)

In [ ]:
# ID_FIDELIDAD
# Variable que identifica si la reserva ha sido realizada por un cliente adscrito
# al programa de fidelización.
#
# Se observa una distribución altamente concentrada, donde el 84,26% de las reservas
# no están asociadas a ningún identificador de fidelidad, mientras que el 15,74%
# restante corresponde a clientes fidelizados.

df_reservas_3["ID_FIDELIDAD"].value_counts(normalize=True)

In [ ]:
# FIDELIDAD
# Variable categórica que indica el programa de fidelización al que pertenece el cliente.
#
# La distribución está fuertemente concentrada en Palladium Rewards (97,92%),
# mientras que WyndHam Rewards (1,16%) y Palladium Connect (0,92%) presentan
# una representación muy reducida.
# no es una variable a tener en cuenta dado el fuerte desblanceo hacia Palladium

df_reservas_3["FIDELIDAD"].value_counts(normalize=True)

In [ ]:
df_reservas_3.head(2)

In [ ]:
#fijamos un valor de cambio para las monedas en dolar.
#Peso Dominicano:   1 USD = 55 RD$
#Peso Mexicano:     1 USD = 19 MEX
#Real:              1 USD = 5,05 REAL BRASIL
#Dolar jamaicano:   1 USD = 153,8 DOLAR JAMAICANO

In [ ]:
# VALHAB
# hay que convertir todo el valor a dolares (USD)
# Variable numérica que representa el precio de la habitación/reserva.
# hay que fijar un tipo de cambio de 2023 y convertir todos los que no tengan de moneda el dolar.

df_reservas_3["VALHAB"].value_counts(normalize=True)

# Crear VALHAB_DOLAR sin modificar VALHAB original
df_reservas_3["MONEDA"] = (
    df_reservas_3["MONEDA"].astype(str).str.strip().str.upper()
)

tipo_cambio_usd = {
    "PESO DOMINICANO": 55,
    "PESO MEXICANO": 19,
    "REAL": 5.05,
    "DOLAR JAMAICANO": 153.8
}

df_reservas_3["VALHAB_DOLAR"] = (
    df_reservas_3["VALHAB"] /
    df_reservas_3["MONEDA"].map(tipo_cambio_usd).fillna(1)
)

In [ ]:
df_reservas_3.head(2)

In [ ]:
#31-38 ERIK
#VALPEN	VALSERV	VALFIJOS	COMERCIALIZADORA	CMVALHAB	CMVALPEN	CMCVALSERV	AUTORIZO
#31	    32	    33	      34	              35	      36	      37	        38
df_reservas_4=df_reservas_3.copy()

In [ ]:
# "VALPEN"
# "VALPEN" representa producción por pensión
# Variable numérica

df_reservas_4["VALPEN"].value_counts(normalize=True)

tipo_cambio_usd = {
    "PESO DOMINICANO": 55,
    "PESO MEXICANO": 19,
    "REAL": 5.05,
    "DOLAR JAMAICANO": 153.8
}

df_reservas_4["VALPEN_DOLAR"] = (
    df_reservas_4["VALPEN"] /
    df_reservas_4["MONEDA"].map(tipo_cambio_usd).fillna(1)
)
# VALPEN se mantiene como variable numérica.
# No se eliminan outliers en esta fase, ya que primero deben analizarse

In [ ]:
# "VALPEN"
# Comprobamos valores valores negativos, ceros y positivos

print("Valores negativos:", (df_reservas_4["VALPEN_DOLAR"] < 0).sum())
print("Valores cero:", (df_reservas_4["VALPEN_DOLAR"] == 0).sum())
print("Valores positivos:", (df_reservas_4["VALPEN_DOLAR"] > 0).sum())

# Hay 576.571 registros con VALPEN = 0, lo que indica reservas sin producción asociada.
# Más adelante se podria crear una variable para separar las reservas con servicios adicionales y las que no.

In [ ]:
# "VALSERV" representa la producción por servicios
# variable numérica
df_reservas_4["VALSERV"].value_counts(normalize=True)

tipo_cambio_usd = {
    "PESO DOMINICANO": 55,
    "PESO MEXICANO": 19,
    "REAL": 5.05,
    "DOLAR JAMAICANO": 153.8
}

df_reservas_4["VALSERV_DOLAR"] = (
    df_reservas_4["VALSERV"] /
    df_reservas_4["MONEDA"].map(tipo_cambio_usd).fillna(1)
)
# Variable muy concentrada en 0
# No tenemos valores negativos
# Se mantiene en el dataset

In [ ]:
# "VALSERV"
# Comprobamos valores valores negativos, ceros y positivos

print("Valores negativos:", (df_reservas_4["VALSERV_DOLAR"] < 0).sum())
print("Valores cero:", (df_reservas_4["VALSERV_DOLAR"] == 0).sum())
print("Valores positivos:", (df_reservas_4["VALSERV_DOLAR"] > 0).sum())

In [ ]:
# "VALSERV"

df_reservas_4["VALSERV"].describe()

# El valor máximo es 4.125, por lo que existen algunos valores extremos que deberán revisarse más adelante en el análisis de outliers.

In [ ]:
# "VALFIJOS"
# VALFIJOS representa la producción fija.
# variable numérica

df_reservas_4["VALFIJOS"].value_counts(normalize=True)

tipo_cambio_usd = {
    "PESO DOMINICANO": 55,
    "PESO MEXICANO": 19,
    "REAL": 5.05,
    "DOLAR JAMAICANO": 153.8
}

df_reservas_4["VALFIJOS_DOLAR"] = (
    df_reservas_4["VALFIJOS"] /
    df_reservas_4["MONEDA"].map(tipo_cambio_usd).fillna(1)
)
# Se mantiene en el dataset

In [ ]:
# "VALFIJOS"

df_reservas_4["VALFIJOS"].describe()

# Se observan valores extremos, minimos y maximos.

In [ ]:
# "COMERCIALIZADORA" indica si la reserva pertenece o no a una comercializadora.
# Es una variable binaria:
# 0 --> No comercializadora
# 1 --> Comercializadora

df_reservas_4["COMERCIALIZADORA"].value_counts(normalize=True)

# Distribucion bastante equilibrada, se mantiene en el dataset
# Se mantiene en el dataset

In [ ]:
# "COMERCIALIZADORA"
# Pasamos la variable a booleana

df_reservas_4["COMERCIALIZADORA"] = df_reservas_4["COMERCIALIZADORA"].astype(bool)

In [ ]:
# "CMVALHAB"
# Representa la producción por habitación asociada a comercializadora.
# Variable numérica

df_reservas_4["CMVALHAB"].value_counts(normalize=True)

tipo_cambio_usd = {
    "PESO DOMINICANO": 55,
    "PESO MEXICANO": 19,
    "REAL": 5.05,
    "DOLAR JAMAICANO": 153.8
}

df_reservas_4["CMVALHAB_DOLAR"] = (
    df_reservas_4["CMVALHAB"] /
    df_reservas_4["MONEDA"].map(tipo_cambio_usd).fillna(1)
)
# Se mantiene en el dataset

In [ ]:
# "CMVALHAB"

df_reservas_4["CMVALHAB"].describe()

In [ ]:
# "CMVALHAB"
# Comprobamos valores valores negativos, ceros y positivos
# Presenta pocos valores negativos y algunos valores extremos,

print("% negativos:", round((df_reservas_4["CMVALHAB"] < 0).mean() * 100, 2))
print("% cero:", round((df_reservas_4["CMVALHAB"] == 0).mean() * 100, 2))
print("% positivos:", round((df_reservas_4["CMVALHAB"] > 0).mean() * 100, 2))

In [ ]:
# "CMVALPEN"
# Representa la producción por pensión asociada a comercializadora
# Variable numérica

df_reservas_4["CMVALPEN"].value_counts(normalize=True)

tipo_cambio_usd = {
    "PESO DOMINICANO": 55,
    "PESO MEXICANO": 19,
    "REAL": 5.05,
    "DOLAR JAMAICANO": 153.8
}

df_reservas_4["CMVALPEN_DOLAR"] = (
    df_reservas_4["CMVALPEN"] /
    df_reservas_4["MONEDA"].map(tipo_cambio_usd).fillna(1)
)

# Se mantiene en el dataset

In [ ]:
# "CMVALPEN"

df_reservas_4["CMVALPEN_DOLAR"].describe()

In [ ]:
# "CMVALPEN"
# Comprobamos valores valores negativos, ceros y positivos

print("Valores negativos:", (df_reservas_4["CMVALPEN"] < 0).sum())
print("Valores cero:", (df_reservas_4["CMVALPEN"] == 0).sum())
print("Valores positivos:", (df_reservas_4["CMVALPEN"] > 0).sum())

# No tiene valores negativos

In [ ]:
# "CMCVALSERV"
# Representa la producción por servicios asociada a comercializadora
# Variable numérica

df_reservas_4["CMCVALSERV"].value_counts(normalize=True)

tipo_cambio_usd = {
    "PESO DOMINICANO": 55,
    "PESO MEXICANO": 19,
    "REAL": 5.05,
    "DOLAR JAMAICANO": 153.8
}

df_reservas_4["CMCVALSERV_DOLAR"] = (
    df_reservas_4["CMCVALSERV"] /
    df_reservas_4["MONEDA"].map(tipo_cambio_usd).fillna(1)
)
# Variable muy desbalanceada, pero se mantiene en esta fase.
# Se evaluará más adelante si aporta capacidad predictiva al modelo.

In [ ]:
# "CMCVALSERV"
# La variable está fuertemente concentrada en el valor 0
# La variable está fuertemente concentrada en el valor 0:
# - El percentil 25 es 0.
# - La mediana es 0.
# - El percentil 75 también es 0.
#
# Esto indica que al menos el 75% de las reservas no tienen producción asociada a servicios de comercializadora.


df_reservas_4["CMCVALSERV"].describe()

In [ ]:
# "CMCVALSERV"
# Comprobamos valores valores negativos, ceros y positivos

print("Valores negativos:", (df_reservas_4["CMCVALSERV"] < 0).sum())
print("Valores cero:", (df_reservas_4["CMCVALSERV"] == 0).sum())
print("Valores positivos:", (df_reservas_4["CMCVALSERV"] > 0).sum())

In [ ]:
# "AUTORIZO"
# Indica quién autoriza o si la reserva ha sido autorizada.
# En los datos se observa que la variable toma principalmente el valor 1.
# La variable está extremadamente desbalanceada y tiene muy poca variabilidad.

df_reservas_4["AUTORIZO"].value_counts(normalize=True)

# No se elimina en esta fase inicial, pero queda marcada como candidata a eliminación si no aporta información relevante en el análisis posterior.

In [ ]:
#39-45 RAUL
#GRATIS	PAIS	SEGMENTO	FUENTE_NEGOCIO
#39	    40	  41	      42
df_reservas_5=df_reservas_4.copy()

#df_reservas_5["GRATIS"].value_counts(normalize=True)
#df_reservas_5["PAIS"].value_counts(normalize=True)
#df_reservas_5["SEGMENTO"].value_counts(normalize=True)
#df_reservas_5["FUENTE_NEGOCIO"].value_counts(normalize=True)

In [ ]:
df_reservas_5.info()

In [ ]:
#GRATIS, indica si la reserva es gratuita o no
#OJO! Variable MUY desbalanceada

df_reservas_5["GRATIS"].value_counts(normalize=True)

In [ ]:
#Las reservas gratuitas tienen una tasa de cancelación significativamente MAS ALTA (50.7%) que las reservas normales (32.7%)
#La MITAD de las reservas gratuitas se acaban cancelando, dato curioso pero al estar tan desbalanceada no se si ayudara
pd.crosstab(df_reservas_5['GRATIS'], df_reservas_5['IS_CANCELLED'], normalize='index')

In [ ]:
df_reservas_5["PAIS"].value_counts(normalize=True).head(15)

In [ ]:
#Para ver los paises con mayor tasa de cancelacion

# Agrupamos por país, contamos cuántas reservas tienen y qué porcentaje cancelan
analisis_paises = df_reservas_5.groupby('PAIS')['IS_CANCELLED'].agg(['count', 'mean'])

# Filtramos para ver países que tengan al menos 100 reservas y ordenamos por tasa de cancelación
analisis_paises[analisis_paises['count'] > 100].sort_values(by='mean', ascending=False).head(20)

In [ ]:
#Vamos a quedarnos con los paises con mas volumen y agrupar los países minoritarios en una categoría común llamada "OTROS"
#Ademas vamos a rescatar y mantener separados a los países que tengan un comportamiento de cancelación extremo.

# OJO! Tenemos una opcion que es "SIN PAIS"

# Mantenemos los de mucho volumen + los que descubrimos con cancelaciones extremas
paises_estrategicos = [
    'ESTADOS UNIDOS', 'MEXICO', 'CANADA', 'BRASIL', 'ARGENTINA',
    'REPUBLICA DOMINICANA', 'ESPAÑA', 'REINO UNIDO', 'ALEMANIA',
    'SIN PAIS',             # Volumen alto y 61% de cancelación
    'COREA DEL SUR',        # ¡85% de cancelación!
    'AFGANISTAN',           # 59% de cancelación
    'EMIRATOS ARABES UNIDOS' # 59% de cancelación
]

# Agrupamos el resto en 'OTROS'
df_reservas_5['PAIS_AGRUPADO'] = df_reservas_5['PAIS'].apply(lambda x: x if x in paises_estrategicos else 'OTROS')

# Verificamos cómo queda la distribución ahora
df_reservas_5['PAIS_AGRUPADO'].value_counts(normalize=True)

In [ ]:
#SEGMENTO, hay datos duplicados -> FIXED RATES

#Homogeneizamos texto
# 1. Pasamos todo a texto, quitamos espacios y convertimos a MAYÚSCULAS en el mismo DataFrame
df_reservas_5['SEGMENTO'] = df_reservas_5['SEGMENTO'].astype(str).str.strip().str.upper()

df_reservas_5["SEGMENTO"].value_counts(normalize=True)

In [ ]:
#Tasa de cancelacion de cada segmento
pd.crosstab(df_reservas_5['SEGMENTO'], df_reservas_5['IS_CANCELLED'], normalize='index')

In [ ]:
#Esta variable esta bien
df_reservas_5["FUENTE_NEGOCIO"].value_counts(normalize=True)

In [ ]:
#Tasa de cancelacion de cada Fuente de Negocio

# Hacemos el crosstab y lo ordenamos de mayor a menor tasa de cancelación
pd.crosstab(df_reservas_5['FUENTE_NEGOCIO'], df_reservas_5['IS_CANCELLED'], normalize='index').sort_values(by=1, ascending=False)

In [ ]:
#creamos las variables indicadas para el modelo

#valor_reserva que es el valor total de la reserva convertido en $
df_reservas_5['valor_reserva_dolar'] = (
    df_reservas_5['VALHAB_DOLAR'] +
    df_reservas_5['VALPEN_DOLAR'] +
    df_reservas_5['VALSERV_DOLAR'] +
    df_reservas_5['VALFIJOS_DOLAR']
)

In [ ]:
#ADR	rev/noches(rn) indica el precio por noche
df_reservas_5['ADR'] =df_reservas_5['valor_reserva_dolar']/df_reservas_5['NOCHES']

In [ ]:
df_reservas_5.head(2)

In [ ]:
#REV PAX	REV/PAX indica el precio por noche
df_reservas_5['REV'] =df_reservas_5['valor_reserva_dolar']/df_reservas_5['PAX']

In [ ]:
df_reservas_5.head(3)

In [ ]:
#se crea variable de antelacion para saber los dias con los que se realiza la cancelacion
df_reservas_5['ANTELACION_DIAS_CANC'] = (
    pd.to_datetime(df_reservas_5['FECHA_CANCELACION']) -
    pd.to_datetime(df_reservas_5['FECHA_TOMA'])
).dt.days

In [ ]:
#exportamos el fichero a csv para su posterior analisis
df_reservas_5.to_csv('df_reservas_clean', index=False)

In [ ]:
df_reservas_clean = pd.read_csv("/content/drive/MyDrive/MDS11_TFM_PALLADIUM/08. MDS11_TFM/df_reservas_clean_reducido.csv" , sep=";")

In [ ]:
df_reservas_clean

In [ ]:
# 1. Definimos el diccionario de mapeo entre ID_HOTEL y su clasificación
size_mapping = {
    # PEQUEÑO (Menos de 250 habitaciones)
    0: 'PEQUEÑO', 19: 'PEQUEÑO', 27: 'PEQUEÑO', 5: 'PEQUEÑO', 97: 'PEQUEÑO',
    99: 'PEQUEÑO', 16: 'PEQUEÑO', 100: 'PEQUEÑO', 20: 'PEQUEÑO', 12: 'PEQUEÑO',
    22: 'PEQUEÑO',

    # MEDIANO (De 250 a 500 habitaciones)
    31: 'MEDIANO', 102: 'MEDIANO', 9: 'MEDIANO', 28: 'MEDIANO', 21: 'MEDIANO',
    24: 'MEDIANO', 14: 'MEDIANO', 26: 'MEDIANO', 98: 'MEDIANO', 25: 'MEDIANO',
    23: 'MEDIANO', 110: 'MEDIANO', 6: 'MEDIANO', 15: 'MEDIANO', 17: 'MEDIANO',
    103: 'MEDIANO', 30: 'MEDIANO',

    # GRANDE (Más de 500 habitaciones)
    32: 'GRANDE', 83: 'GRANDE', 94: 'GRANDE', 92: 'GRANDE', 96: 'GRANDE',
    106: 'GRANDE', 107: 'GRANDE'
}

# 2. Creamos la nueva columna "SIZE" cruzando la columna "ID_HOTEL" con el diccionario
df_reservas_clean['SIZE'] = df_reservas_clean['ID_HOTEL'].map(size_mapping)

# 3. Comprobamos la distribución de la nueva columna en el dataset
print(df_reservas_clean['SIZE'].value_counts(dropna=False))

In [ ]:
pd.set_option("display.max_columns",None)

In [ ]:
df_reservas_clean

In [ ]:
#exportamos el fichero a csv para su posterior analisis
df_reservas_clean.to_csv('df_reservas_clean_reducido_size', index=False)